services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    networks:
      - default

  app:
    build:
      context: .  # Указываем путь к Dockerfile
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"  # Порт для вашего приложения
    networks:
      - default

  front:
    build:
      context: ./training_arc_front
      dockerfile: Dockerfile
    depends_on:
      - app
    ports:
      - "5173:5173"
    networks:
      - default

  minio:

    image: 'minio/minio:latest'
    environment:
      MINIO_ROOT_USER: tsoyka
      MINIO_ROOT_PASSWORD: qwertyui
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - default
    volumes:
      - minio:/app/minio/
    command: server /data --console-address ":9001"


networks:
  default:
    driver: bridge

volumes:
  minio:
    external:
      true