services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    networks:
      - default

  app:
    build:
      context: .  # Указываем путь к Dockerfile
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8000:8000"  # Порт для вашего приложения
    networks:
      - default

networks:
  default:
    driver: bridge