--liquibase formatted sql
--changeset kemerovqq:1
create table if not exists client(
    id int generated by default as identity,
    login text unique not null,
    age int check (age > 0),
    email text unique not null,
    minio_path text default null,
    created_at timestamp default now()
);